language: node_js
node_js: 
  - "stable"
cache:
  yarn: true
  directories:
    - "node_modules"

services:
  - postgresql
  - redis-server

# create test db
before_script:
  - psql -c 'create database typegraphql_sample_test;' -U postgres
  - psql -c "create user max with password 'maxondria';" -U postgres
  - yarn
  - yarn global add typescript mocha
# command to run tests
script:
  - yarn test
  # - coverage run --source='.' --omit='run.py' manage.py test
  # - coverage report

# generate code climate report
# after_script:
#   - codeclimate-test-reporter

# push report to coveralls.io
# after_success:
#   - coveralls